command_timeout = 1000

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = '[➜](bold green)'

[git_status]
untracked = '[ $count](bold yellow) '
staged = '[ $count](bold green) '
stashed = "[ ](cyan) "
deleted = '[ $count](bold red) '
modified = '[ $count](bold blue) '
behind = '[ ](bold purple) '
ahead = '[ ](bold purple) '
format = '([$all_status$ahead_behind]($style))'
[git_metrics]
disabled = false

[lua]
symbol = " "
