# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
# "$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# [[input.prepend_keymap]]
# on   = "<Esc>"
# run  = "close"
# desc = "Cancel input"
[mgr]
prepend_keymap = [
{on="y" , run = ['''
    shell 'echo "$@" | xclip -i -selection clipboard -t text/uri-list' --confirm
    ''', "yank"]},
{ on   = "<Enter>", run  = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
{ on   = "p", run  = "plugin smart-paste", desc = "Paste into the hovered directory or CWD" },
{ on  = [ "T" ], run  = "shell 'tmux new-window' --interactive", desc  = "Open tmux from current directory" },
{ on  = [ "g","g" ], run  = "shell lazygit --block --confirm", desc  = "Open lazygit from current directory" },
{ on = "2", run = "tab_switch 1", desc = "Switch to the second tab" },
]

