git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never --syntax-theme="OneHalfDark"


gui:
  scrollHeight: 12
  scrollOffMargin: 4

# Keybindings
# keybinding:
#   universal:
#     scrollUpMain-alt1: <
    # scrollDownMain-alt1: <c-a-j>
